export const ADD_HISTORY = 'ADD_HISTORY';
export const FAILED_HISTORY = 'FAILED_HISTORY';

export const ADD_USERS = 'ADD_USERS';
export const USERS_FAILED = 'USERS_FAILED';

// export const ADD_DECORATIONS = 'ADD_DECORATIONS';
// export const DECORATION_FAILED = 'DECORATION_FAILED';